services:
  ML:
    build: .
    image: joy-ml2
    container_name: joy-ml
    volumes:
      - ./:/workspace
    ipc: host # important for PyTorch dataloaders
    runtime: nvidia
    privileged: true
    command: bash -c "while true; do sleep 1; done"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
