services:
  ML:
    build: .
    image: joy-ml2
    container_name: joy-ml
    ports:
      - "60000:8888"
    volumes:
      - ./:/workspace
    ipc: host # important for PyTorch dataloaders
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
